[project]
name = "movie-backend-api"
version = "0.1.0"
description = "Api movie lens(mock)"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.116.1",
    "pandas>=2.3.1",
    "sqlalchemy>=2.0.42",
    "httpx>=0.28.1",
    "pydantic>=2.11.3",
    "uvicorn>=0.34.0"
]
