[project]
name = "movie-backend-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.116.1",
    "pandas>=2.3.1",
    "sqlalchemy>=2.0.42",
]
